-- ----------------------------
-- Table structure for "C##FHADMIN"."TB_OUTLINEOUTLINE"
-- ----------------------------
-- DROP TABLE "C##FHADMIN"."TB_OUTLINEOUTLINE";
CREATE TABLE "C##FHADMIN"."TB_OUTLINEOUTLINE" (
	"USERNAME" VARCHAR2(255 BYTE) NULL ,
	"REALM" VARCHAR2(255 BYTE) NULL ,
	"PASSWORD" VARCHAR2(255 BYTE) NULL ,
	"REGISTER" VARCHAR2(255 BYTE) NULL ,
	"TYPE" VARCHAR2(255 BYTE) NULL ,
	"PORT" NUMBER(11) NULL ,
	"TIMEOUT" NUMBER(11) NULL ,
	"INCOMING_TYPE" VARCHAR2(255 BYTE) NULL ,
	"INCOMING_IVR" VARCHAR2(255 BYTE) NULL ,
	"INCOMING_EXTEN" NUMBER(11) NULL ,
	"INCOMING_CALLCENTER" VARCHAR2(255 BYTE) NULL ,
	"EFFECTIVE_CALLER_ID_NAME" VARCHAR2(255 BYTE) NULL ,
	"FORCE_EFFECTIVE_CALLER_ID_NAME" VARCHAR2(255 BYTE) NULL ,
	"TYPE_BLACKLIST" VARCHAR2(255 BYTE) NULL ,
	"OUTLINE_ID" VARCHAR2(100 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN "C##FHADMIN"."TB_OUTLINEOUTLINE"."USERNAME" IS '外线号码';
COMMENT ON COLUMN "C##FHADMIN"."TB_OUTLINEOUTLINE"."REALM" IS '服务器地址';
COMMENT ON COLUMN "C##FHADMIN"."TB_OUTLINEOUTLINE"."PASSWORD" IS '注册密码';
COMMENT ON COLUMN "C##FHADMIN"."TB_OUTLINEOUTLINE"."REGISTER" IS '是否注册';
COMMENT ON COLUMN "C##FHADMIN"."TB_OUTLINEOUTLINE"."TYPE" IS '外线类型';
COMMENT ON COLUMN "C##FHADMIN"."TB_OUTLINEOUTLINE"."PORT" IS '端口号';
COMMENT ON COLUMN "C##FHADMIN"."TB_OUTLINEOUTLINE"."TIMEOUT" IS '外线呼叫超时时间';
COMMENT ON COLUMN "C##FHADMIN"."TB_OUTLINEOUTLINE"."INCOMING_TYPE" IS '外线呼入类型';
COMMENT ON COLUMN "C##FHADMIN"."TB_OUTLINEOUTLINE"."INCOMING_IVR" IS '外线呼入IVR';
COMMENT ON COLUMN "C##FHADMIN"."TB_OUTLINEOUTLINE"."INCOMING_EXTEN" IS '呼入分机';
COMMENT ON COLUMN "C##FHADMIN"."TB_OUTLINEOUTLINE"."INCOMING_CALLCENTER" IS '呼入队列';
COMMENT ON COLUMN "C##FHADMIN"."TB_OUTLINEOUTLINE"."EFFECTIVE_CALLER_ID_NAME" IS '外线显示信息';
COMMENT ON COLUMN "C##FHADMIN"."TB_OUTLINEOUTLINE"."FORCE_EFFECTIVE_CALLER_ID_NAME" IS '外线强制显示信息';
COMMENT ON COLUMN "C##FHADMIN"."TB_OUTLINEOUTLINE"."TYPE_BLACKLIST" IS '黑名单类型';
COMMENT ON COLUMN "C##FHADMIN"."TB_OUTLINEOUTLINE"."OUTLINE_ID" IS 'ID';

-- ----------------------------
-- Indexes structure for table TB_OUTLINEOUTLINE
-- ----------------------------

-- ----------------------------
-- Checks structure for table "C##FHADMIN"."TB_OUTLINEOUTLINE"

-- ----------------------------

ALTER TABLE "C##FHADMIN"."TB_OUTLINEOUTLINE" ADD CHECK ("OUTLINE_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "C##FHADMIN"."TB_OUTLINEOUTLINE"
-- ----------------------------
ALTER TABLE "C##FHADMIN"."TB_OUTLINEOUTLINE" ADD PRIMARY KEY ("OUTLINE_ID");
