
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `TB_OUTLINEOUTLINE`
-- ----------------------------
DROP TABLE IF EXISTS `TB_OUTLINEOUTLINE`;
CREATE TABLE `TB_OUTLINEOUTLINE` (
 		`OUTLINE_ID` varchar(100) NOT NULL,
		`USERNAME` varchar(255) DEFAULT NULL COMMENT '外线号码',
		`REALM` varchar(255) DEFAULT NULL COMMENT '服务器地址',
		`PASSWORD` varchar(255) DEFAULT NULL COMMENT '注册密码',
		`REGISTER` varchar(255) DEFAULT NULL COMMENT '是否注册',
		`TYPE` varchar(255) DEFAULT NULL COMMENT '外线类型',
		`PORT` int(11) NOT NULL COMMENT '端口号',
		`TIMEOUT` int(11) NOT NULL COMMENT '外线呼叫超时时间',
		`INCOMING_TYPE` varchar(255) DEFAULT NULL COMMENT '外线呼入类型',
		`INCOMING_IVR` varchar(255) DEFAULT NULL COMMENT '外线呼入IVR',
		`INCOMING_EXTEN` int(11) NOT NULL COMMENT '呼入分机',
		`INCOMING_CALLCENTER` varchar(255) DEFAULT NULL COMMENT '呼入队列',
		`EFFECTIVE_CALLER_ID_NAME` varchar(255) DEFAULT NULL COMMENT '外线显示信息',
		`FORCE_EFFECTIVE_CALLER_ID_NAME` varchar(255) DEFAULT NULL COMMENT '外线强制显示信息',
		`TYPE_BLACKLIST` varchar(255) DEFAULT NULL COMMENT '黑名单类型',
  		PRIMARY KEY (`OUTLINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
