GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE TB_OUTLINEOUTLINE (
 		OUTLINE_ID  nvarchar(100) NOT NULL,
		USERNAME nvarchar(255) DEFAULT NULL,
		REALM nvarchar(255) DEFAULT NULL,
		PASSWORD nvarchar(255) DEFAULT NULL,
		REGISTER nvarchar(255) DEFAULT NULL,
		TYPE nvarchar(255) DEFAULT NULL,
		PORT int NOT NULL,
		TIMEOUT int NOT NULL,
		INCOMING_TYPE nvarchar(255) DEFAULT NULL,
		INCOMING_IVR nvarchar(255) DEFAULT NULL,
		INCOMING_EXTEN int NOT NULL,
		INCOMING_CALLCENTER nvarchar(255) DEFAULT NULL,
		EFFECTIVE_CALLER_ID_NAME nvarchar(255) DEFAULT NULL,
		FORCE_EFFECTIVE_CALLER_ID_NAME nvarchar(255) DEFAULT NULL,
		TYPE_BLACKLIST nvarchar(255) DEFAULT NULL,
PRIMARY KEY CLUSTERED 
(
	[OUTLINE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
